name: Codacy Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          output: results.sarif
          format: sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
